### ISSUE TITLE
Teil in der QM ist kaputt-nachbearbeitet worden

### ISSUE THREAD

**Issue by felixdoerre** [parttimenerd/Moderne-Physik#11]
"Bereich mit E > V (k^2>0) klassisch erlaubt" wurde durch eine kaputte fallunterscheidung zerstört.

E>V -> erlaubt -> Wellen (war mal erster Fall)
E<V -> verboten -> exponentielles Endringen (war mal letzter Fall)

**Comment by parttimenerd** [comment]
Ich verstehe deine Anmerkung leider nicht.
Im Tex steht

```
\item[Bereich mit $E > V$ ($k^2 > 0$)] klassisch erlaubt.
\item[Bereich mit $E = V$ ($k^2 = 0$)] klassische Umkehrpunkte.
\item[Bereich mit $E < V$ ($k^2 < 0$)] klassisch verboten.
```

Das scheint mir korrekt zu sein.

**Comment by felixdoerre** [comment]
Ja, der Teil ist ok... der Teil drunter erklärt das aber falsch beim 
"verboten, E<V" muss exponentielles Eindringen sein da hast du aber 
sinuse, und dann hast du da 2mal denselben fall.. ... usw...

Am 09.07.2015 um 18:48 schrieb Johannes Bechberger:
