### ISSUE TITLE
Hamilton-Operator in 4.2 (Schroedinger-Gleichung) vermutlich falsch

### ISSUE THREAD

**Issue by Fiona-J-W** [parttimenerd/Moderne-Physik#13]
Im genannten Abschnitt definierst du den Hamilton-Operator wie folgt:

H = (v^2)/(2m) + V(r)

Tofu und ich vermuten, dass hier eigentlich

H = (p^2)/2m + V(r)

gemeint ist, da sonst die Dimension nicht Energie ist und der folgende Abschnitt nicht nachvollziehbar wird.

**Comment by parttimenerd** [comment]
Hmm... Da scheinst du recht zu haben. Wäre cool, wenn du diesen Fehler korrigieren würdest und dann einen Pull Request absetzen könntest.
