### ISSUE TITLE
In blatt 12 Mechanik aufgabe 1 ist ein r \to \rho

### ISSUE THREAD

**Issue by felixdoerre** [parttimenerd/Moderne-Physik#23]

**Comment by felixdoerre** [comment]
ich mach das jetzt

**Comment by parttimenerd** [comment]
Danke

**Comment by felixdoerre** [comment]
was hast du da gepusht? ich hab doch gesagt dass ich das mach jetzt will mein commit nichtmehr!

**Comment by felixdoerre** [comment]
ich hab jetzt deinen commit reverted und dafür meinen rein (weil ich hab nicht nur renamed glaub ich) das ist in #24

**Comment by parttimenerd** [comment]
Oh... Tut mir leid
